name: Update Workflow Permissions

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  update-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Update workflow permissions
        run: echo "This workflow exists solely to set the appropriate permissions for GitHub Actions"
