name: Simple Build & Deploy

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

# Set permissions for GitHub token
permissions:
  contents: write    # This is required for actions/checkout and creating releases
  packages: write    # This is required for publishing packages

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd, imagick, mbstring
          coverage: none
        
      - name: PHP Syntax Check
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l

  build-release:
    name: Build Release Package
    needs: validate
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create build directory
        run: |
          mkdir -p build/wp-image-optimizer

      - name: Copy files to build directory
        run: |
          rsync -av --exclude='.git/' --exclude='.github/' --exclude='build/' . build/wp-image-optimizer/

      - name: Create plugin zip
        run: |
          cd build
          zip -r wp-image-optimizer-${{ steps.get_version.outputs.VERSION }}.zip wp-image-optimizer

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/wp-image-optimizer-${{ steps.get_version.outputs.VERSION }}.zip
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## WebP & AVIF Image Optimizer ${{ steps.get_version.outputs.VERSION }}
            
            See [CHANGELOG.md](CHANGELOG.md) for details.
